import { IRegionInterface } from "../interfaces/region.interface";

export const regionsOfUkraine: IRegionInterface[] = [
  {
    id: 1,
    nameUK: "Вінницька область",
    nameEN: "Vinnytsia region",
    nameRU: "Винницкая область",
  },
  {
    id: 2,
    nameUK: "Волинська область",
    nameEN: "Volyn region",
    nameRU: "Волынская область",
  },
  {
    id: 3,
    nameUK: "Дніпропетровська область",
    nameEN: "Dnipropetrovsk region",
    nameRU: "Днепропетровская область",
  },
  {
    id: 4,
    nameUK: "Донецька область",
    nameEN: "Donetsk region",
    nameRU: "Донецкая область",
  },
  {
    id: 5,
    nameUK: "Житомирська область",
    nameEN: "Zhytomyr region",
    nameRU: "Житомирская область",
  },
  {
    id: 6,
    nameUK: "Закарпатська область",
    nameEN: "Transcarpathian region",
    nameRU: "Закарпатская область",
  },
  {
    id: 7,
    nameUK: "Запорізька область",
    nameEN: "Zaporizhzhia region",
    nameRU: "Запорожская область",
  },
  {
    id: 8,
    nameUK: "Івано-Франківська область",
    nameEN: "Ivano-Frankivsk region",
    nameRU: "Ивано-Франковская область",
  },
  {
    id: 9,
    nameUK: "Київська область",
    nameEN: "Kyiv region",
    nameRU: "Киевская область",
  },
  {
    id: 10,
    nameUK: "Кіровоградська область",
    nameEN: "Kirovohrad region",
    nameRU: "Кировоградская область",
  },
  {
    id: 11,
    nameUK: "Луганська область",
    nameEN: "Luhansk region",
    nameRU: "Луганская область",
  },
  {
    id: 12,
    nameUK: "Львівська область",
    nameEN: "Lviv region",
    nameRU: "Львовская область",
  },
  {
    id: 13,
    nameUK: "Миколаївська область",
    nameEN: "Mykolaiv region",
    nameRU: "Николаевская область",
  },
  {
    id: 14,
    nameUK: "Одеська область",
    nameEN: "Odesa region",
    nameRU: "Одесская область",
  },
  {
    id: 15,
    nameUK: "Полтавська область",
    nameEN: "Poltava region",
    nameRU: "Полтавская область",
  },
  {
    id: 16,
    nameUK: "Рівненська область",
    nameEN: "Rivne region",
    nameRU: "Ровенская область",
  },
  {
    id: 17,
    nameUK: "Сумська область",
    nameEN: "Sumy region",
    nameRU: "Сумская область",
  },
  {
    id: 18,
    nameUK: "Тернопільська область",
    nameEN: "Ternopil region",
    nameRU: "Тернопольская область",
  },
  {
    id: 19,
    nameUK: "Харківська область",
    nameEN: "Kharkiv region",
    nameRU: "Харьковская область",
  },
  {
    id: 20,
    nameUK: "Херсонська область",
    nameEN: "Kherson region",
    nameRU: "Херсонская область",
  },
  {
    id: 21,
    nameUK: "Хмельницька область",
    nameEN: "Khmelnytskyi region",
    nameRU: "Хмельницкая область",
  },
  {
    id: 22,
    nameUK: "Черкаська область",
    nameEN: "Cherkasy region",
    nameRU: "Черкасская область",
  },
  {
    id: 23,
    nameUK: "Чернівецька область",
    nameEN: "Chernivtsi region",
    nameRU: "Черновицкая область",
  },
  {
    id: 24,
    nameUK: "Чернігівська область",
    nameEN: "Chernihiv region",
    nameRU: "Черниговская область",
  },
  { id: 25, nameUK: "місто Київ", nameEN: "Kyiv city", nameRU: "город Киев" },
  {
    id: 26,
    nameUK: "Автономна Республіка Крим",
    nameEN: "Autonomous Republic of Crimea",
    nameRU: "Автономная Республика Крым",
  },
];
